{
 "title": "Monitoramento de Link de internet",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes", "label": "Download" }
   ],
   "targets": [
    {
     "application": { "filter": "Teste de velocidade" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": { "filter": "Download" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Teste de velocidade" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": {
      "filter": "Ping(disponibilidade de internet)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de internet (tempo real)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": {
      "filter": "Incoming network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PIng",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms", "label": "PIng" }
   ],
   "targets": [
    {
     "application": { "filter": "Teste de velocidade" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": {
      "filter": "Ping(disponibilidade de internet)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Data e hora real do teste de velocidade",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Teste de velocidade" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": { "filter": "Data" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Melhor servidor baseado em ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Teste de velocidade" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": { "filter": "Servidor" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decmbytes", "label": "Upload" }
   ],
   "targets": [
    {
     "application": { "filter": "Teste de velocidade" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "srvInternet" },
     "item": { "filter": "Upload" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}